"""initial migrations

Revision ID: 221e719b7853
Revises: 
Create Date: 2024-01-13 11:36:48.894582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221e719b7853'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('foreign_key', 'unique', 'nullable', 'primary_key', name='validconstraints'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_ref_pk', sa.String(), nullable=False),
    sa.Column('fk_rel', sa.String(), nullable=False),
    sa.Column('fk_model_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=True),
    sa.Column('last_public_id_created', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('api_token', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_token'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrylist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_key_value', sa.Text(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tableparameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data_type', sa.Enum('string', 'text', 'integer', 'boolean', 'date', 'datetime', name='datatypes'), nullable=False),
    sa.Column('primary_key', sa.Boolean(), nullable=True),
    sa.Column('foreign_key_reference_field', sa.String(), nullable=True),
    sa.Column('dataType_length', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('tableparameter_id', sa.Integer(), nullable=True),
    sa.Column('entry_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_list_id'], ['entrylist.id'], ),
    sa.ForeignKeyConstraint(['tableparameter_id'], ['tableparameter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrylist_relationships',
    sa.Column('relationship_id', sa.Integer(), nullable=True),
    sa.Column('entrylist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entrylist_id'], ['entrylist.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationship.id'], )
    )
    op.create_table('parameter_constraint',
    sa.Column('tableparameter_id', sa.Integer(), nullable=True),
    sa.Column('constraint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constraint_id'], ['constraint.id'], ),
    sa.ForeignKeyConstraint(['tableparameter_id'], ['tableparameter.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameter_constraint')
    op.drop_table('entrylist_relationships')
    op.drop_table('entry')
    op.drop_table('tableparameter')
    op.drop_table('entrylist')
    op.drop_table('table')
    op.drop_table('api')
    op.drop_table('user')
    op.drop_table('relationship')
    op.drop_table('constraint')
    # ### end Alembic commands ###
